spring:
  application:
    name: registroProjetos

  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  jwt:
    secret: ${JWT_SECRET:AKHNBAJBFHABFHABFHABFH756743764gsgAFDGFADGAHDFVB**¨&¨%¨%$%$#$%#$&*¨*&((*)(_)(*gGAFHAGBFHYAHFG))}
    expiration-ms: 28800000

  datasource:
    url: jdbc:h2:mem:gtidb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  jwt:
    secret: ${JWT_SECRET:AKHNBAJBFHABFHABFHABFH756743764gsgAFDGFADGAHDFVB**¨&¨%¨%$%$#$%#$&*¨*&((*)(_)(*gGAFHAGBFHYAHFG))}
    expiration-ms: 28800000

app:
  cors:
    allowed-origins: http://localhost:5173

---
spring:
  config:
    activate:
      on-profile: prod
  jwt:
    secret: ${JWT_SECRET:AKHNBAJBFHABFHABFHABFH756743764gsgAFDGFADGAHDFVB**¨&¨%¨%$%$#$%#$&*¨*&((*)(_)(*gGAFHAGBFHYAHFG))}
    expiration-ms: 28800000

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gtidb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: ${PORT:8080}
  jwt:
    secret: ${JWT_SECRET:AKHNBAJBFHABFHABFHABFH756743764gsgAFDGFADGAHDFVB**¨&¨%¨%$%$#$%#$&*¨*&((*)(_)(*gGAFHAGBFHYAHFG))}
    expiration-ms: 28800000

app:
  cors:
    allowed-origins: ${FRONTEND_URL:https://seu-dominio.com}
  jwt:
    secret: ${JWT_SECRET:AKHNBAJBFHABFHABFHABFH756743764gsgAFDGFADGAHDFVB**¨&¨%¨%$%$#$%#$&*¨*&((*)(_)(*gGAFHAGBFHYAHFG))}
    expiration-ms: 28800000