spring:
  application:
    name: registroProjetos
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:gtidb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

app:
  cors:
    allowed-origins: ${FRONTEND_URL:http://localhost:5173}
  jwt:
    secret: ${JWT_SECRET:AKHNBAJBFHABFHABFHABFH756743764gsgAFDGFADGAHDFVBAHAHDJAHDJAH8676AOqwqieSlspoOILKLkslKSLkslk))}
    expiration-ms: 28800000